# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "JSConf Australia 2016"
email: "team@jsconfau.com"
description: "A one day conference bringing together developers and the future of the web."
baseurl: ""
url: ""
ticket_url: "http://ti.to/cssconf-au/2016/"
collections:
  - team

# Build settings
markdown: kramdown
exclude: [vendor]
